version: "3.9"

services:
  db:
    image: postgres:14.0-alpine
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    networks:
      - backend
    restart: always
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - backend
    restart: always
    command:
      - "./gunicorn.sh"
  controller:
    build: .
    depends_on:
      - db
    networks:
      - backend
    restart: always
#    command:
#      - CMD ["python", "/server/event_controller.py"]

networks:
  backend:
    driver: bridge