version: "3.9"

services:
  db:
    container_name: db_events
    image: postgres:14.0-alpine
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
#      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_HOST="0.0.0.0"
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always

  web:
    container_name: web
    build: .
    ports:
      - "8080:8080"
#    network_mode: host
    depends_on:
      - db
    links:
      - db
#    env_file:
#      - .env
    restart: always
#    command: bash ./gunicorn.sh
#    command:
#      - python wsgi.py


#  controller:
#    container_name: event_controller
#    #    env_file:
##      - .env
#    build: .
#    environment:
#      - DB_SERVER=kanban-postgres
##    depends_on:
##      - db
#    links:
#      - db
#    restart: always
#    command: python server/event_controller.py
