version: "3.9"

services:
  db:
    image: postgres:14.0-alpine
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - backend
    links:
      - db
    env_file:
      - .env
    restart: always
    command: bash ./gunicorn.sh

  controller:
    env_file:
      - .env
    build: .
    depends_on:
      - db
    networks:
      - backend
    links:
      - db
    restart: always
    command: python server/event_controller.py

networks:
  backend:
    driver: bridge