version: "3.9"

services:
  db:
    image: postgres:14.0-alpine
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - DATABASE=postgres
#      - USERNAME=postgres
#      - PASSWORD=postgres
#      - HOST=127.0.0.1

#     command: python data_base/__main__.py
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
#        ipv4_address: 172.16.238.20
#        ipv6_address: 2001:3984:3989::20
    restart: always

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - backend
    links:
      - db
    env_file:
      - .env
    restart: always
    command: bash ./gunicorn.sh

  controller:
    env_file:
      - .env
    build: .
    depends_on:
      - db
    networks:
      - backend
    links:
      - db
    restart: always
    command: python server/event_controller.py

networks:
  backend:
    driver: bridge