"""Init migration

Revision ID: 1f0b50644442
Revises: 
Create Date: 2022-11-17 19:03:10.193849

"""
from sqlalchemy import Column, func
from sqlalchemy.dialects.postgresql import (INTEGER, TIMESTAMP, BOOLEAN, VARCHAR, ARRAY)

from alembic import op
import datetime
from sqlalchemy.dialects import postgresql
from data_base import DefaultSettings


# revision identifiers, used by Alembic.
revision = '1f0b50644442'
down_revision = None
branch_labels = None
depends_on = None

settings = DefaultSettings()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        settings.TBL_EVENTS,
        Column('event_id', INTEGER, primary_key=True),
        Column('event_name', VARCHAR(127), nullable=False),
        Column('time_start', TIMESTAMP, nullable=False),
        Column('time_end', TIMESTAMP, nullable=False),
        Column('description', VARCHAR),
        Column('url_pdf', VARCHAR(255)),
        Column('people_count', INTEGER, nullable=False),
        Column('coefficient', INTEGER, default=1),
        Column('users_id_want', ARRAY(INTEGER), default={}),
        Column('users_id_go', ARRAY(INTEGER), default={}),
        Column('image', VARCHAR(127)),
    )
    op.create_table(
        settings.TBL_USERS,
        Column('user_id', INTEGER, primary_key=True),
        Column('user_isu_number', INTEGER),
        Column('user_name', VARCHAR(127), nullable=False),
        Column('user_surname', VARCHAR(127), nullable=False),
        Column('user_patronymic', VARCHAR(127), nullable=False),
        Column('phone', VARCHAR(127)),
        Column('vk_link', VARCHAR(127)),
        Column('mail', VARCHAR(127)),
        Column('is_russian_citizenship', BOOLEAN),
        Column('score', INTEGER),
        Column('ban_date', TIMESTAMP),
        Column('notify_id', ARRAY(INTEGER), default={}),
        Column('time_select_finish', TIMESTAMP),
    )
    op.create_table(
        settings.TBL_NOTIFIES,
        Column('notify_id', INTEGER, primary_key=True),
        Column('event_id', INTEGER, nullable=False),
        Column('time', TIMESTAMP, default=func.now()),
        Column('notify_header', VARCHAR(127)),
        Column('notify_data', VARCHAR),
        )
    op.create_table(
        settings.TBL_NEWS,
        Column('news_id', INTEGER, primary_key=True),
        Column('header', VARCHAR(127), nullable=False),
        Column('data', VARCHAR),
        Column('time', TIMESTAMP),
    )
    op.create_table(
        settings.TBL_SSO_PUB_KEY,
        Column("kid", VARCHAR, unique=True, primary_key=True),
        Column("kty", VARCHAR),
        Column("alg", VARCHAR),
        Column("use", VARCHAR),
        Column("n", VARCHAR),
        Column("e", VARCHAR),
        Column("expires", TIMESTAMP, default=datetime.datetime.now()),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(settings.TBL_EVENTS)
    op.drop_table(settings.TBL_USERS)
    op.drop_table(settings.TBL_NOTIFIES)
    op.drop_table(settings.TBL_NEWS)
    op.drop_table(settings.TBL_SSO_PUB_KEY)
    # ### end Alembic commands ###
