"""Table for urls

Revision ID: 111111111111
Revises: 
Create Date: 2022-09-25 15:43:25.973097

"""
from sqlalchemy import Column, func
from sqlalchemy.dialects.postgresql import (INTEGER, TIMESTAMP, BOOLEAN, VARCHAR, ARRAY)

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "111111111111"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        Column('event_id', INTEGER, primary_key=True),
        Column('event_name', VARCHAR(127), nullable=False),
        Column('time_start', TIMESTAMP, nullable=False),
        Column('time_end', TIMESTAMP, nullable=False),
        Column('description', VARCHAR),
        Column('url_pdf', VARCHAR(255)),
        Column('people_count', INTEGER, nullable=False),
        Column('coefficient', VARCHAR, default=1),
        Column('users_id_want', ARRAY(INTEGER), default={}),
        Column('users_id_go', ARRAY(INTEGER), default={}),
        Column('image', VARCHAR(127)),
    )
    op.create_table(
        "user",
        Column('user_id', INTEGER, primary_key=True),
        Column('user_isu_number', INTEGER),
        Column('user_name', VARCHAR(127), nullable=False),
        Column('user_surname', VARCHAR(127), nullable=False),
        Column('user_patronymic', VARCHAR(127), nullable=False),
        Column('phone', VARCHAR(127)),
        Column('vk_link', VARCHAR(127)),
        Column('mail', VARCHAR(127)),
        Column('is_russian_citizenship', BOOLEAN),
        Column('score', INTEGER),
        Column('ban_date', TIMESTAMP),
        Column('notify_id', ARRAY(INTEGER), default={}),
        Column('time_select_finish', TIMESTAMP),
    )
    op.create_table(
        "notify",
        Column('notify_id', INTEGER, primary_key=True),
        Column('event_id', INTEGER, nullable=False),
        Column('time', TIMESTAMP, default=func.now()),
        Column('notify_header', VARCHAR(127)),
        Column('notify_data', VARCHAR),
        )
    op.create_table(
        "news",
        Column('news_id', INTEGER, primary_key=True),
        Column('header', VARCHAR(127), nullable=False),
        Column('data', VARCHAR),
        Column('time', TIMESTAMP),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    op.drop_table("user")
    op.drop_table("notify")
    op.drop_table("news")
    # ### end Alembic commands ###
